### ISSUE TITLE
DH bug

### ISSUE THREAD

**Issue by Addonman** [baffler/Quartz-Procs-Module#1]
On demon hunter i get this

Error occured in: Global
Count: 1
Message: ..\AddOns\Quartz_Procs\quartzprocs.lua line 155:
attempt to call method 'returnProcList' (a nil value)
Debug:
(tail call): ?
Quartz_Procs\quartzprocs.lua:155:
Quartz_Procs\quartzprocs.lua:99
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9:
[string "safecall Dispatcher[1]"]:5
(tail call): ?
...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:644:
...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:636
Locals:

**Comment by baffler** [comment]
[v3.63](https://github.com/baffler/Quartz-Procs-Module/releases/tag/v3.63) will fix your issue
